[package]
name = "hyper-rustls"
version = "0.15.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
ct-logs = "0.4"
futures = "0.1.21"
http = "0.1"
hyper = "0.12"
rustls = "0.14"
tokio-io = "0.1.1"
tokio-rustls = "0.8"
tokio-tcp = "0.1"
webpki = "0.18.1"
webpki-roots = "0.15"

[dev-dependencies]
tokio = "0.1"

[replace]
"webpki:0.18.1" = { git = "https://github.com/passchaos/webpki", rev = "251388" }